source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-livereload'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]

group :development, :test do
    gem 'capybara'
    gem 'pry'
    gem 'pry-byebug'
    gem 'rspec'
    gem 'haml'
end
